### ISSUE TITLE
Updating to Gradle 4.10-rc2 breaks the plugin declarations in java-gradle-plugin

### ISSUE THREAD

**Issue by Stvad** [gradle/kotlin-dsl#1049]
### Expected Behavior
When I run gradle with the following sample plugin https://github.com/gradle/kotlin-dsl/blob/master/samples/gradle-plugin/plugin/build.gradle.kts it builds successfully 

### Current Behavior
When I run gradle build I get the following error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/sitalov/Dropbox/SoftwareEngineering/Experiments/kotlin/kotlin-dsl/samples/gradle-plugin/plugin/build.gradle.kts' line: 12

* What went wrong:
PluginDeclaration with name 'myPlugin' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10-rc-2/userguide/command_line_interface.html#sec:command_line_warnings
```

### Context
I was trying to switch to using 4.10 to take advantage of recursive composite builds, but doing so breaks the plugin build 😢 

### Steps to Reproduce (for bugs)
* Clone download a [sample plugin project](https://github.com/gradle/kotlin-dsl/blob/master/samples/gradle-plugin/plugin/build.gradle.kts)
* Change version of gradle in the wrapper to 4.10-rc2
* Run `./gradlew`

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/rdi3euenkfbbk

**Comment by StefMa** [comment]
Yep, the Syntax is wrong.
You have to use "create("my Plugin")".
That is a breaking change in the latest release.
See the release notes for more...

**Comment by Stvad** [comment]
I looked through latest release notes (Both for Gradle and for Kotlin-DSL) and was not able to find a reference to this =\. I'd appreciate if you could share a link.

**Comment by StefMa** [comment]
Take a look into the `Breaking Changes` section [here](https://github.com/gradle/kotlin-dsl/releases/tag/v1.0-RC3):
> **Container String invoke now is named() instead of maybeCreate()**

Since the `plugins` block is a [`NamedDomainObjectContainer`](https://docs.gradle.org/4.10-rc-2/javadoc/org/gradle/api/NamedDomainObjectContainer.html) you have to use `create()` or `register()` (depends on which minimum Gradle version you want to support):
<img width="402" alt="bildschirmfoto 2018-08-19 um 18 33 39" src="https://user-images.githubusercontent.com/10229883/44310912-8b4dd080-a3de-11e8-8f0d-8b678e4bdc7d.png">

You can also take a look into the last commit from the `develop` branch where the sample is updated:
https://github.com/gradle/kotlin-dsl/blob/301c444e35b11e5ea1aeb075706ccee2bef2e2ca/samples/gradle-plugin/plugin/build.gradle.kts#L12

**Comment by Stvad** [comment]
Ah, I misinterpreted that entry. Thank you for the references!
