### ISSUE TITLE
Configurations cannot be configured with a lambda using generated accessors

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#1082]
### Expected Behavior
The following snippets to work:
```kotlin
plugins {
    java
}

configurations {
    implementation {
        resolutionStrategy.activateDependencyLocking()
    }
}

configurations.implementation {
        resolutionStrategy.activateDependencyLocking()
}
```

### Current Behavior
```
^ Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
```

----

What works is the following:
```kotlin
plugins {
    java
}

configurations.implementation.resolutionStrategy.activateDependencyLocking()

configurations.getByName("implementation") {
    resolutionStrategy.activateDependencyLocking()
}

configurations {
    "implementation" {
        resolutionStrategy.activateDependencyLocking()
    }
}
```

### Context
https://github.com/gradle/gradle/pull/6515

### Your Environment
Gradle 4.10

**Comment by eskatos** [comment]
One solution would be to introduce a public type in the Gradle API to capture the fact that things are configurable. Something equivalent to the internal `org.gradle.util.Configurable`. Then we can add an `invoke` operator extension on it in the Kotlin DSL.

**Comment by bamboo** [comment]
Hi @3flex,

The solution is to change the expression `configuration.compile` to `configuration.compile.get()`.

This is due to the Kotlin DSL now favouring the lazy Gradle configuration API (#917), `configurations.compile` is no longer a `Configuration` but a provider of `Configuration` thus the need for calling `get()` on it.

**Comment by bamboo** [comment]
Closing as fixed in f46852ed404c478dd054ee493b8a7450114ddb54.

**Comment by 3flex** [comment]
Thanks for the quick reply!

Am I safe (or at least no worse off than before) with `configurations.getByName("compile")` or `configurations["compile"]`?

Only because https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/ shows usage of `configurations["name"]`. Or doe guide need updating?

**Comment by bamboo** [comment]
Yes, you are safe with either choice.

The suggestions in the guide, in general, try to preserve the semantics of the original Groovy code, that's why `configurations["name"]` is used.
