### ISSUE TITLE
Polyfill groovy's .execute() in Kotlin?

### ISSUE THREAD

**Issue by ebraminio** [gradle/kotlin-dsl#1126]
Maybe not an accepted issue even, when I ported my project build file to Kotlin the main difference was I hadn't access to `.execute()` from [Groovy](https://github.com/ebraminio/DroidPersianCalendar/commit/289f97349595d65bbec669917988796d2c5e759b#diff-16b7be338ef38d40c385574302ec1668L19) and I had to put a [custom one here](https://github.com/ebraminio/DroidPersianCalendar/commit/289f97349595d65bbec669917988796d2c5e759b#diff-60e6842f8cb614050f71b00fd285b430R8), maybe kotlin-dsl can polyfill that?

**Comment by StefMa** [comment]
From my point of view this is an **Groovy** feature which is just not available in **Kotlin**.
Therefore I would not add this to the Kotlin DSL.
Otherwise the Project have add addional features from the Groovy language to the DSL 😄 

Beside of this:
I don't recommend you to add the `versionSuffix` with this. This makes the Gradle build unnecessary "slow". Think about the following:
Do you **really** need to add this suffix to each *debug* build? Isn't it enough to add it when you release a version (as Beta maybe)? This will make the daily development a little bit fast.
But this is another topic ;) No need to answer here. Just a small tip :)

**Comment by ebraminio** [comment]
Ok, so lets close this and let us know if any update happens. Thanks
