### ISSUE TITLE
Unresolved reference war.getWebAppDir()

### ISSUE THREAD

**Issue by rahulkhimasia** [gradle/kotlin-dsl#1250]
In my project I apply the WAR plugin and have call war.getWebAppDir(). 
In Gradle 4.10.2 which has kotlin DSL 1.0-rc-6 that call works file.
But in Gradle 5.0-rc-3 which has Kotlin DSL 1.0.3 that call fails with the message Unresolved reference : getWebAppDir

### Your Environment

 * Build scan URL:

**Comment by rahulkhimasia** [comment]
I have distilled my relevant source code into the attached file. 
[MultiProjectRoot.tar.gz](https://github.com/gradle/kotlin-dsl/files/2591997/MultiProjectRoot.tar.gz)

Here are the steps you need to execute to reproduce my problem. 

1. tar --extract --gunzip --file MultiProjectRoot.tar.gz
2. cd MultiProjectRoot
3. gradle :WarProject1:simpleTask1

**Comment by eskatos** [comment]
Thanks @rahulkhimasia, I can reproduce now.

Gradle 5 introduced accessors for tasks, meaning in your `WarProject1/build.gradle.kts` script:
```kotlin
tasks {
    create("simpleTask") {
        println(war.webAppDir)
    }
}
```
`war` now resolves to `tasks.war` which is the `War` task, instead of resolving to `project.war` which is the `WarPluginConvention` that has this `webAppDir` property. The `War` task doesn't.

You need to disambiguate as follow:
```kotlin
tasks {
    create("simpleTask") {
        println(project.war.webAppDir)
    }
}
```

This can be discovered by either navigating to the source of `webAppDir` from your IDE, or printing `war` to get to know what it is.

This is expected and part of Gradle 5.0 changes, closing.
