### ISSUE TITLE
Gradle SourceSets in another file won't resolve

### ISSUE THREAD

**Issue by Kerooker** [gradle/kotlin-dsl#1324]
Following from [This StackOverflow Question](https://stackoverflow.com/questions/54329251/unresolved-reference-sourcesets-gradle-kotlin-dsl-in-another-file) and a discussion in KotlinLang's slack:

This is a completely valid structure in Groovy:

build.gradle:

```
apply plugin: 'java'
apply from: 'gradle/test.graadle'
```

gradle/test.gradle:

```
sourceSets {
    unitTest {
        compileClasspath += main.output
        runtimeClasspath += main.output
    }
}
```

However, when trying to do the same thing from Kotlin KTS, it won't work:

```
build.gradle.kts:

plugins {
    java
}

apply(from = "gradle/test.gradle.kts")
```
gradle/test.gradle.kts:

```
sourceSets {
    create("unitTest") {
     // Do configurations
    }
}
```
`Line 1: import org.gradle.kotlin.dsl.sourceSets
                                       ^ Unresolved reference: sourceSets`

This seems to be related to https://github.com/gradle/kotlin-dsl/issues/1287. It's very frustrating to try to convince people to use Kotlin Gradle DSL while an amazingly basic syntax doesn't work

**Comment by eskatos** [comment]
Here's the equivalent `gradle/test.gradle.kts` script:

```kotlin
configure<SourceSetContainer> {
    val main by getting
    named("unitTest") {
        compileClasspath += main.output
        runtimeClasspath += main.output
    }
}
```

Because `gradle/test.gradle.kts` is a plugin script applied using `apply(from = "..")` it can't benefit from the Kotlin DSL type-safe accessors to dynamic model elements, here `sourceSets {}` for the `SourceSetContainer` extension and the `main` and `unitTest` source sets.

See the documentation for more information https://docs.gradle.org/current/userguide/kotlin_dsl.html#type-safe-accessors

**Comment by hmarggraff** [comment]
eskatos solution does not work for me: SourceSet with name 'itest' not found.
