### ISSUE TITLE
Using AbstractCopyTask with source sets is not discoverable

### ISSUE THREAD

**Issue by reitzig** [gradle/kotlin-dsl#1373]
We might expect this to work:

```kotlin
val sourcesJar by creating(Jar::class) {
    classifier = "sources"
    from(sourceSets.main)
}
```

While it type checks, it fails at runtime; `from` can't handle `SourceSetContainer` parameters.

`from(sourceSets.main.get())` also type checks but similarly doesn't work. We end up having to write

```kotlin
 from(sourceSets.main.get().allSource)
```

which is not only ugly but also hard-ish to discover (which is one of the big advantages of Kotlin DSL, imho).

It would be great if `from` could handle source sets better, or if there was a dedicated method for it.

**Comment by StefMa** [comment]
Is this working with the gradle dsl? 🤔

**Comment by JLLeitschuh** [comment]
I think this is more relevant in the gradle/gradle repository. I think that one of the devs can move this issue for you.

CC: @big-guy

**Comment by reitzig** [comment]
@StefMa I _think_ the two behave the same here.

@JLLeitschuh Since the Groovy DSL doesn't care about types (or does it?) I figured at least that part of the "complaint" would better fit here. If the shared API has to be changed to accomodate by request, then the main repository is probably a better fit, agreed.

**Comment by eskatos** [comment]
Whichever the DSL, the `from()` call doesn't know how to handle a `SourceSet` because it is not enough for Gradle to know what you want to use from that source set. It could be `sourceSets.main.outputs` for example. You have to explicitly write that you want the sources. Please have a look at `from()`'s javadoc for details about what types you can pass to it.

Gradle will also fail in the same way with the Groovy DSL if you do:
```groovy
// build.gradle
tasks.register("sourcesJar", Jar) {
    classifier = "sources"
    from(sourceSets.main)
}
```

Here's how you can pass all source of a source set with the Groovy DSL:

```groovy
// build.gradle
tasks.register("sourcesJar", Jar) {
    classifier = "sources"
    from(sourceSets.main.allSource)
}
```

With the Kotlin DSL, the `sourceSets.main` accessor isn't a `SourceSet`, but a `Provider<SourceSet>` for lazy configuration, you need to either eagerly `.get()` the source set first:

```kotlin
// build.gradle.kts
from(sourceSets.main.get().allSource)
```

or lazily map it to the sources:

```kotlin
// build.gradle.kts
from(sourceSets.main.map { it.allSource })
```

This is equivalent to the following Groovy:
```groovy
// build.gradle
from(sourceSets.named("main").get().allSource)
// or lazily
from(sourceSets.named("main").map { it.allSource })
```

**Comment by reitzig** [comment]
@eskatos Thanks for the explanation! While it doesn't make lots of sense to me that a set of sources would contain anything but sources, I see that that is beyond the scope of Kotlin DSL.

Still, I think `from` should be more narrowly typed to that the initial example I give is _statically_ detected as invalid.

**Comment by eskatos** [comment]
@reitzig, I'm going to close this question as answered, please open an issue on `gradle/gradle` about enhancing the api if you feel strongly about it
