### ISSUE TITLE
Move gradle-kotlin-dsl and distro snapshots to another repository

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#271]
We shouldn't be publishing public artefacts to `repo.gradle.org`.

**Comment by NicolasRouquette** [comment]
I wanted to document how I plan to use this plugin -- even though it's at the bleeding edge of development -- and was expecting to find in https://github.com/gradle/gradle-script-kotlin/blob/master/README.md some info about where the bleeding edge versions are available for configuring the gradle wrapper. 

Currently, it's not obvious for a gradle+kotlin newbie like me to figure out the details of the configuration; in particular, the distributionUrl in 'gradle/wrapper/gradle-wrapper.properties'; e.g:

      distributionUrl=https\://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-3.5-20170224224706+0000-all.zip

Since this is bleeding-edge dev; I suppose that these versions will change often.
I think it would be helpful to provide a link to where the dev versions are available; currently:

https://repo.gradle.org/gradle/webapp/#/artifacts/browse/tree/General/dist-snapshots

It would be very helpful if the build metadata in Artifactory could include cross-references to the github issues that have been fixed in a particular build.

**Comment by eskatos** [comment]
Superseded by #1232
