### ISSUE TITLE
Creating project syntax

### ISSUE THREAD

**Issue by sksamuel** [gradle/kotlin-dsl#405]
No example I can find on the net will show me how to use the gradle `project("submodule")` syntax:

```kotlin
project("domain") {
  dependencies {
    compile("org.apache.commons:commons-dbcp2:2.1.1")
    compile("org.jasypt:jasypt:1.9.2")
  }
}
```

Syntax is fine in intellij, but each time I try to run gradlew clean jar, we get `> Configuration with name 'compile' not found`.

**Comment by sksamuel** [comment]
I notice that non of the samples have a compile block in dependencies, other than compile kotlin. So I wonder if this works at all ?

**Comment by eskatos** [comment]
Hi @sksamuel,

This should do:
```kotlin
project(":domain") {

    // needs to be applied for the "compile" configuration to be created
    apply { plugin("java") } // or kotlin, ymmv

    dependencies {
        "compile"("org.apache.commons:commons-dbcp2:2.1.1")
        "compile"("org.jasypt:jasypt:1.9.2")
    }
}
```

**Comment by sksamuel** [comment]
Thanks Paul I'll give that a go.

**Comment by jaredsburrows** [comment]
@eskatos You should be able to use `compile` directly if you have a `project-schema.json`, right? I am in my current project.

**Comment by eskatos** [comment]
@jaredsburrows in the example above, the root project doesn't have a `compile` configuration so no accessor, either with automatic accessor generation or a `project-schema.json` file. Here we need to reference the `compile` configuration by `String` because we apply the `java` plugin to a subproject without using the `plugins` block.

I'm closing this issue as the original question should be resolved.
