### ISSUE TITLE
Script plugins can be applied using the plugins {} DSL

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#424]

**Comment by eskatos** [comment]
This work will take place with the following steps:
1. make it work with the Groovy DSL in Gradle proper, including breaking changes for the Kotlin DSL to accomodate with
2. impact the Kotlin DSL to absorb the breaking changes without adding support for script plugins applied using the plugins block
3. implement script plugins applied using the plugins block in the Kotlin DSL

Depending on our findings along the way we may need to loop over changes in Gradle proper and the Kotlin DSL.

Step 1.  is currently being worked on at https://github.com/gradle/gradle/tree/pm/plugins-dsl/script-plugins

We made progress in allowing script plugins to be applied using the plugins DSL by introducing a new type of `PluginDependencySpec`, a `ScriptPluginDependencySpec` which is defined via the new script "path" dependency builder:

```kotlin
plugins {
  script("path/to/other.gradle")
  script("https://example.com/another.gradle")
}
```

By defining a new entry point in the DSL we make sure only attributes that make sense for script plugins can be specified.

And departing from the current `apply from: "path"` semantics, script paths are assumed to be relative to the requesting script, instead of the root project directory. We think this makes for clearer semantics, specially in the remote case and will allow remote script plugins to define their dependencies on other remote script plugins using relative paths.

At the time of writing, one issue remains for step 1: duplicate build operations events for script plugin application (from both `PluginManager` and `ScriptPlugin`).

This work also need to be rebased as https://github.com/gradle/gradle/pull/2600 has now been merged.

Reviewing for naming, responsibilities split, right abstractions and so on will be done next once the build operations are fixed.

**Comment by oehme** [comment]
What will be the plugin ID of such a script? 

```
plugins {
  script("path/to/other.gradle")
  script("https://example.com/another.gradle")
}
```

**Comment by bamboo** [comment]
The short answer is none.

In the long run it will be up for the user to assign an ID either via the `pluginManagement` or `plugins` DSL. For instance:

```kotlin
plugins {
  script("https://foo.bar/...") identifiedBy "foo" apply false
}

plugins.withId("foo") {
  // conditional logic depending on plugin being applied or not
}

// later...
if (someCondition) {
  apply { plugin("foo") }
}
```

**Comment by bamboo** [comment]
There are two aspects to plugin identities:

 - providing an user identifiable handle for `plugins.withId(...)`, build operations, build scans, etc

 - `apply once` semantics: based on `java.lang.Class` identity (the user handle has no influence here, the same plugin Class can be referenced through more than one user handle, e.g., `com.acme.foo` and `acme-foo` could both point to the same `implementation-class`)

By default, script plugins are unidentified in the first sense but always identified in the second one by the generated `Plugin` `java.lang.Class` instances that are cached by `resolved script uri` thus preserving `apply once` semantics (the same script content coming from two different remote uris would be applied twice though).

To improve upon the `apply once` behaviour described above we want to:

 - use the script content hash instead of the resolved script uri as the `java.lang.Class` cache key

 - potentially cache the script content within the generated `java.lang.Class`

This can be done while maintaining the scripts unidentified by default as part of upcoming stories.

As a side note, given those two aspects we can conclude there are no real script plugins Today since `apply from` is only about applying scripts to one or more objects. The applied script it not really a plugin since it doesn't have any plugin semantics like user identifiable handles or `apply once`.

**Comment by eskatos** [comment]
The two improvements to the `apply once` behaviour mentioned above are now on the feature branch.

**Comment by eskatos** [comment]
Pull-request with infrastructure and Groovy support opened: https://github.com/gradle/gradle/pull/2825

Once this is merged Kotlin support can be worked on.
