### ISSUE TITLE
IDEA doesn't show parameter name hints correctly

### ISSUE THREAD

**Issue by pioterj** [gradle/kotlin-dsl#437]
IDEA doesn't seem to show parameter name hints correctly in Kotlin DSL.

See the screenshot below. It should display "id:" hint instead of "p0:".

<img width="463" alt="screen shot 2017-07-21 at 12 46 02" src="https://user-images.githubusercontent.com/1292566/28463493-f198a260-6e20-11e7-8940-3dccab6dcabe.png">

Encountered in Gradle 4.1, IDEA 2017.2, Kotlin 1.1.3.

**Comment by bamboo** [comment]
The fix is probably to preserve the parameter names in the generated Gradle API jar.

**Comment by bamboo** [comment]
Upon further inspection this seems to be caused by Kotlin interface delegation (`... : Project by project { ...`) not preserving the parameter names in the generated bytecode.

Parameter names show up correctly for non delegated members, for instance, notice the `version` parameter below:

![screen shot 2017-07-21 at 10 32 31 am](https://user-images.githubusercontent.com/51689/28465674-fe24a6da-6dff-11e7-9d67-d0001099da38.png)

**Comment by bamboo** [comment]
Superseded by #464
