### ISSUE TITLE
Gradle consumes plugin portal as a regular maven repository

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#469]
Since #389 it's no longer necessary to use the custom plugin resolution protocol.

Gradle should consume the plugin portal as a regular maven repository and the custom plugin resolution protocol code removed.

**Comment by bamboo** [comment]
@oehme, how important do you think this is?

**Comment by eskatos** [comment]
Doing this would enable plugin resolution to reach included builds, see https://github.com/gradle/gradle/issues/2528#issuecomment-334086991 ; by so reducing the workarounds needed to use the `plugins {}` block  until https://github.com/gradle/gradle/issues/2528 is fixed ; e.g. in this [settings.gradle](https://github.com/eskatos/composite-gradle-plugins-build/blob/ab4486945fe385a45159af1a538236c0c89fad87/settings.gradle#L3-L7) file.

It would also make all plugin repositories regular repositories, not a special case anymore. Then `Settings.pluginManagement.repositories` is a regular `RepositoryHandler`. Fixing e.g. https://github.com/gradle/gradle/issues/3169 by the way and incurring less work to adapt the DSL for Kotlin.

Plugin resolution could also consider all "plugin repositories" when resolving each plugin. Fixing https://github.com/gradle/gradle/issues/3210 by the way.

This would also be a step towards supporting more dependency resolution features for plugins like dynamic versions, see https://github.com/gradle/gradle/issues/1370.

Note that with regards to the Kotlin DSL, changing the type of Settings DSL elements is a breaking change once #56 gets released. I think this alone is a good argument for tackling this sooner rather than later.

Quite a bunch of code would get removed 🎉, simplifying plugin resolution. Tests and fixtures should be adapted.

**Comment by bamboo** [comment]
Thanks for the great summary, @eskatos!

>  I think this alone is a good argument for tackling this sooner rather than later.

I agree.

**Comment by eskatos** [comment]
Upstream PR https://github.com/gradle/gradle/pull/3347

**Comment by eskatos** [comment]
Upstream PR merged, closing as delivered
