### ISSUE TITLE
Feature: new sample hello-kotlin-js

### ISSUE THREAD

**Issue by guenhter** [gradle/kotlin-dsl#470]
Like the `hello-android` project it would be very helpful to have a `hallo-java-script` because with the actual gradle 4.1 release I'm not able to get this right any more.

This should be covered:
https://kotlinlang.org/docs/tutorials/javascript/getting-started-gradle/getting-started-with-gradle.html

**Comment by eskatos** [comment]
Hi @guenhter, thanks for the issue.
What are the issues you're having?
We'd like to have such a sample, would you consider contributing it?

**Comment by guenhter** [comment]
Hi, I'd love to contribute it, but due to my lack of understanding of new kotlin-dsl, I failed to do so. In my repo https://github.com/guenhter/kotlin-noob I already have a couple of projects (3 JVM based and one JS based) but the JS-based one is not longer working (I guess since gradle 4.1).

**Comment by eskatos** [comment]
@guenhter, I opened a small pull-request against your repository that fix the build script for your `kotlin-js` module, see the comments there: https://github.com/guenhter/kotlin-noob/pull/1

**Comment by guenhter** [comment]
@eskatos Thanks for the PR. I updated some compiler options in that project and I guess this could be used as JavaScript sample (if you want to use it).

**Comment by eskatos** [comment]
Sure.

Here is some guidance that I hope will be helpful:
- create a `samples/hello-kotlin-js-world` directory
- populate it with a Gradle Kotlin DSL project, maybe start from the existing `samples/hello-kotlin-world`
- tweak the new sample build to produce Javascript

We'll then need to find a way to actually test this sample in order to prevent any regression.
I need to think about this, we don't want to fire a browser for the sole purpose of testing this.

You can use the following command to validate that your sample pass some basic tests:
```shell
./gradlew samples-test:test --tests="*SamplesSmokeTest"
```

Feel free to start on the pull-request!
Please remember to work from the `develop` branch of this repository.

Thanks!

**Comment by eskatos** [comment]
This has been delivered by #478 
Closing
