### ISSUE TITLE
Extra Defaults change in commit c21eba6d looses type information

### ISSUE THREAD

**Issue by sic-bre** [gradle/kotlin-dsl#512]
Commit c21eba6d does more than "Adjust code to nullability changes in the Gradle API".  Previously when using extra defaults to access gradle properties the information of the type of the property was maintained.  Now the type of the property comes back as Any and I've a had to add casts in contexts where the type is important.  This change was made in response to in Gradle 4.2 the PropertyState setter having the @Nullable annotation applied.

### Expected Behavior

Instead I suggest that the type value passed in the Kotlin Extension should have been changed from T to T? rather than Any.  Allowing a nullable value signature but preserving types for code that uses the extra property types.

### Current Behavior

In ExtraPropertiesExtensions.kt value was changed from T to Any on setValue to "accommodate a change in nullablity".  However this changes looses the type information that was previously passed.

operator fun ExtraPropertiesExtension.setValue(receiver: Any?, property: KProperty<*>, value: **Any**) =  set(property.name, value)

Several other places in the file the type was changed from T to **T: Any**.

### Context

I have created a plugin that depended on the extra property extensions passing correct type information.  This worked as expected in Gradle 4.1 but with Gradle 4.2 latest type signature change this type information is getting removed and replaced with Any.

### Steps to Reproduce (for bugs)
Functional change in type signatures.

### Your Environment
Behavior changed between Gradle 4.1 and Gradle 4.2.  The commit that made the change was made https://github.com/gradle/kotlin-dsl/commit/21eba6dc6e8d3a672c530e680481a1b367ef031f

**Comment by JLLeitschuh** [comment]
I think this is the change being referred to by @sic-bre:
https://github.com/gradle/kotlin-dsl/commit/21eba6dc6e8d3a672c530e680481a1b367ef031f#diff-e6df212bc9b2bc8b63741a3b7078ff5bL37

**Comment by bamboo** [comment]
Thanks for the report, @sic-bre, we'll look into it.

**Comment by eskatos** [comment]
One of the underlying issue is that `ExtraPropertiesExtension` in the Gradle API does not declare nullability properly.

- [`Object get(String name)`](https://github.com/gradle/gradle/blob/b0032a8a355379e5868b22d660f8be5cf857168e/subprojects/core-api/src/main/java/org/gradle/api/plugins/ExtraPropertiesExtension.java#L121) method should be `@Nullable`
- [`void set(String name, Object value)`](https://github.com/gradle/gradle/blob/b0032a8a355379e5868b22d660f8be5cf857168e/subprojects/core-api/src/main/java/org/gradle/api/plugins/ExtraPropertiesExtension.java#L142) method's `value` parameter should be `@Nullable`

This should be fixed first.

**Comment by eskatos** [comment]
Fixed in #516, closing
