### ISSUE TITLE
Support settings.gradle written in Kotlin

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#56]
How would Gradle detect a Kotlin based setting file?

What would be the implications, if any, for external tools that rely on the naming convention?

**Comment by adammurdoch** [comment]
One such tool would be the tooling api. For this, we might insist that a build that uses a kotlin settings script must also have wrapper properties file. Or even that every build must have a wrapper properties file.

**Comment by oehme** [comment]
+1 for requiring wrapper.properties. 

There's other reasons to use that file more often. E.g. in Buildship the user might not be using a wrapper (because of some draconian "no jars in the repo" policy), but still want to benefit from a fixed Gradle version.

**Comment by eskatos** [comment]
A `ScriptPluginFactoryProvider` should advertise a *default settings file name* and both Gradle's `BuildLayoutFactory` should use that to detect which file to use.

See also #37 for automatic detection of `build.gradle.kts` build files.

Side node, Composite Builds requires a build to have a settings file. This validation happens in the`IncludedBuildFactory` and should be updated accordingly.

**Comment by eskatos** [comment]
Main blocker was IntelliJ not recognizing builds with no `build.gradle` nor `settings.gradle` files.
Since Kotlin 1.1.5, IntelliJ does when there's a `build.gradle.kts` file. This issue is now actionable and not blocked on https://github.com/gradle/gradle/issues/1994 anymore.

Three steps:
1. #527 Gradle should use the `ScriptingLanguages` SPI to find settings scripts
2. #528 Kotlin DSL should support `Settings` as a script target
3. #529 Kotlin DSL model builders should support settings script to provide classpath to IDEs

**Comment by bamboo** [comment]
Closing as delivered.
