### ISSUE TITLE
tasks.withType type parameter constraint is too restrictive

### ISSUE THREAD

**Issue by ilya-g** [gradle/kotlin-dsl#575]
I can't configure all verification tasks using `withType` function in the following way:

```
tasks.withType<VerificationTask> {
    ignoreFailures = false
}
```

The `VerificationTask` is an interface that does not extend `Task`.

`withType` is declared as following: 

```
fun <reified S : Any> DomainObjectCollection<in S>.withType(crossinline configuration: S.() -> Unit)
```

`TaskContainer` is a `DomainObjectCollection<Task>`. Therefore only `Task` and its subtypes can be used as `S`.

### Your Environment

kotlin-dsl embedded in Gradle 4.2

**Comment by ilya-g** [comment]
I believe `in S` projection is not appropriate here, because the function doesn't put anything _into_ the collection.

**Comment by mkobit** [comment]
Another unfortunate thing is, I think in Groovy it just kind of works because Groovy throws out generic information.

```groovy
tasks.withType(VerificationTask) {
   ignoreFailures = false
}
```

I haven't tried that, but I think it actually works.

Other types that also impacts are:

* https://docs.gradle.org/current/javadoc/org/gradle/process/JavaForkOptions.html
* https://docs.gradle.org/current/javadoc/org/gradle/process/ProcessForkOptions.html

**Comment by bamboo** [comment]
I agree. The constraint is inherited from the Gradle API so we first need to change it there:

 * https://github.com/gradle/gradle/blob/b0032a8a355379e5868b22d660f8be5cf857168e/subprojects/core-api/src/main/java/org/gradle/api/DomainObjectCollection.java#L44

**Comment by eskatos** [comment]
Closing in favor of upstream https://github.com/gradle/gradle/issues/4050
