### ISSUE TITLE
Kotlin 1.2

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#617]
https://blog.jetbrains.com/kotlin/2017/11/kotlin-1-2-released/

**Comment by eskatos** [comment]
Since `1.1.60` Gradle integration tests fail, e.g. https://builds.gradle.org/viewLog.html?buildId=9564164&tab=queuedBuildOverviewTab

Looking at [one test](https://builds.gradle.org/repository/download/Gradle_Check_Quick_Java7_Oracle_Windows_integTest/9617891:id/report-integTest-integTest.zip%21/classes/org.gradle.integtests.CustomPluginIntegrationTest.html#can%20reference%20plugin%20in%20buildSrc%20by%20id) we can see that `:buildSrc:compileJava` succeeded but the produced `.class` files did not end up in the build script classpath. In fact, no `.class` file was produced despite compilation task success. All other failing integration tests are a variation of this.

This is very easily reproduced on the command line:

```
// Main.java
public class Main {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
```

Then,

`javac -cp /path/to/kotlin-compiler[-embeddable].jar Main.java`

returns `0`. But silently fails to compile anything, no `.class` file produced. 

Upstream issue https://youtrack.jetbrains.com/issue/KT-21537

**Comment by eskatos** [comment]
`kotlin-compiler-embeddable` jar should not be part of the `javac` classpath in the first place.
It only happens when the `InProcessGradleExecuter` fixture is in use.

The solution seems to be to make the `InProcessGradleExecuter` more closely replicate the module registry classpath setup.

**Comment by eskatos** [comment]
So, the root cause was a badly relocated `javaslang` in `kotlin-compiler-embeddable`
This will be fixed in an upcoming Kotlin version but we have a workaround: removing `META-INF/services/javax.annotation.processing.Processor` which is unused but cause the failure.

**Comment by bamboo** [comment]
Gradle Master check against the latest `kotlin-dsl` snapshot is green: https://builds.gradle.org/viewLog.html?buildId=9671691&tab=buildResultsDiv&buildTypeId=Gradle_Check_Stage_MasterAccept_Trigger
