### ISSUE TITLE
Dependency declaration DSL non-uniformly supports collections of dependency notations

### ISSUE THREAD

**Issue by eskatos** [gradle/kotlin-dsl#639]
### Current Behavior
When given a collection of dependency notations, in Kotlin:
```kotlin
dependencies {
    compile(listOf("a:b:1.0", "c:d:2.0"))
}
```
the build configuration fails with the following error:
```
> Cannot convert the provided notation to an object of type DirectDependency: [a:b:1.0, c:d:2.0].
    The following types/formats are supported:
    - Instances of DirectDependency.
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().
    
    Comprehensive documentation on dependency notations is available in DSL reference for DependencyHandler type.
```

It does work with Groovy DSL build scripts.

### Expected Behavior
When given a collection of dependency notations, the build configuration succeeds. Just as with Groovy DSL build scripts.

### Context
Found out about this issue while converting existing build scripts that rely on this Groovy DSL feature.

Interestingly it seems the support is not advertised in the error message nor in the DSL reference.

[DynamicAddDependencyMethods](https://github.com/gradle/gradle/blob/4f1d8d59b25bd37665f26843f6886216a63a4ffd/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DynamicAddDependencyMethods.java#L29) is responsible for the Groovy DSL only support. It is used in both [DefaultDependencyHandler](https://github.com/gradle/gradle/blob/4f1d8d59b25bd37665f26843f6886216a63a4ffd/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyHandler.java#L78) and [DefaultDependencyConstraintHandler](https://github.com/gradle/gradle/blob/4f1d8d59b25bd37665f26843f6886216a63a4ffd/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DefaultDependencyConstraintHandler.java#L41).

Another thing to consider is that the Groovy DSL support does [recursively flatten the given collections](https://github.com/gradle/gradle/blob/4f1d8d59b25bd37665f26843f6886216a63a4ffd/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DynamicAddDependencyMethods.java#L53).

**Comment by JLLeitschuh** [comment]
Isn't this an upstream Gradle API issue?

**Comment by bamboo** [comment]
@JLLeitschuh It is.

**Comment by eskatos** [comment]
Issue moved to [gradle/gradle #7649](https://github.com/gradle/gradle/issues/7649) via [**ZenHub**](https://www.zenhub.com/)

**Comment by magJ** [comment]
Assuming https://github.com/gradle/gradle/issues/7649 gets fixed, this will mean that there will still be no support for `varargs` style dependency declaration correct?

IE, defining the dependencies without using `listOf`, as supported in the groovy dsl.
```kotlin
dependencies {
    compile("a:b:1.0", "c:d:2.0")
}
 ```

**Comment by StefMa** [comment]
I think it does depending on the implementation. If it's get implemented as
suggested in the issue then you have to wrap it into a list.
But when it gets implemented as an array of strings then a vararg should be
possible I think...

**Comment by magJ** [comment]
@StefMa Looking into this a bit more, it sadly doesn't seem like it will be possible to support varargs via the kotlin-dsl, at least not without breaking the existing API.  
The main issue is that adding a varargs overload to the configuration accessors or `DependencyHandlerScope`, causes resolution ambiguity issues with group/name/version/... variants.  
This isn't an issue in the groovy-dsl, as it simply uses map literals(rather than named arguments) for the same functionality.  

Bit of a shame really, at least in the projects I work on, varargs dependency declaration is used very heavily, while map based dependency declaration is virtually non-existent. 
So it's painful to have to give up on that widely used convenient syntax, because of some convenience functions I don't need. 

I can partially work around this by creating my own `DependencyHandlerScope` class with the map helper functions removed and a varargs function added, putting this into `buildSrc` and overriding the `Project.dependencies` function works well enough.
However I don't think there is any way of creating a similar version of the type-safe accessors, at least not without using a custom kotlin-dsl distribution.
If there is a way of doing this as a plugin, id like to know.
