### ISSUE TITLE
Sample with  custom sourceSet

### ISSUE THREAD

**Issue by Alcheorg** [gradle/kotlin-dsl#650]
How to add custom sourceSet?
Groovy:
```
sourceSets {
    main {
        proto {
            srcDir 'proto'
        }
    }
}
```
Kotlin???
//part of usage part of usage of protobuf plugin for example

**Comment by StefMa** [comment]
I found this https://github.com/gradle/kotlin-dsl/issues/443 and https://github.com/gradle/kotlin-dsl/issues/515
Hope it will point you to the right direction...

**Comment by eskatos** [comment]
@Alcheorg I think you are looking at configuring the Protobuf source set, not adding a new one.
In other words you need to configure the `ProtobufSourceSet` convention of the `main` source set.

Here's how you would do it:

```kotlin
java.sourceSets {
    "main" {
        withConvention(ProtobufSourceSet::class) {
            proto {
                srcDir("proto")
            }
        }
    }
}
```

Which can be shortened to:
```kotlin
java.sourceSets["main"].withConvention(ProtobufSourceSet::class) {
    proto {
        srcDir("proto")
    }
}
```

HTH

**Comment by Alcheorg** [comment]
There is no ProtobufSourceSet class at https://github.com/google/protobuf-gradle-plugin, but all works on groovy. Is it necessary to have ProtobufSourceSet.class at project for kotlin-dsl?

**Comment by StefMa** [comment]
Maybe @eskatos means this one?

https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/ProtobufSourceDirectorySet.groovy

**Comment by Alcheorg** [comment]
No, in that case we have error:
Could not find any convention object of type ProtobufSourceDirectorySet.
It is not easy task)

**Comment by StefMa** [comment]
I've just tried it out and the following works for me:
```kotlin
plugins {
  id("java")
  id("com.google.protobuf") version("0.8.3")
}

java.sourceSets {
  getByName("main") {
    getJava().srcDir("proto")
  }
}
```

Everything in gradle-kotlin is a little bit "complicated" because you have to find out which methods you have call.
In a nutshell:
* To customize the sourceSets see the [sourceSet method](https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:sourceSets(groovy.lang.Closure))
* The closure is a [SourceSetContainer](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SourceSetContainer.html)
* This `SourceSetContainer` extends from [`NamedDomainObjectCollection`](https://docs.gradle.org/current/javadoc/org/gradle/api/NamedDomainObjectCollection.html) which have `<T> getByName()`.
* According to `SourceSetContainer` the generic `T` is a [`SourceSet`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SourceSet.html)
* In `SourceSet` you  can get the `main` sourceset by calling [`getJava`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SourceSet.html#getJava--) (which returns a [`SourceDirectorySet`](https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html)
* On this `SourceDirectorySet` you can set the `srcDir`. [See here](https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html#srcDir-java.lang.Object-).

Yep, that's basically its :)
You only have to know how to read the Gradle Javadocs 🙃
