### ISSUE TITLE
Precompiled script plugins can use type-safe accessors for extensions contributed by declared external plugin dependencies

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#673]
A precompiled script plugin that declares a dependency on an external plugin, say, the `java` plugin, should be able to reference the contributed extensions such as `sourceSets` via a type-safe accessor:

```
plugins {
    java
}

sourceSets.main {
    // ...
}
```

## Implementation notes
Accessors should be private/internal to each precompiled script plugin (`internal object $pluginId-accessors  { ... }`) where applicable.

**Comment by bamboo** [comment]
Originally spiked in 6506a878e28dc6f18f9aaf83f926bec789bd13f2

**Comment by bamboo** [comment]
Resolved in Gradle 5.3-RC1.

**Comment by madorb** [comment]
I am not sure that i am sure that this is the issue i'm running into, but in `buildSrc/com/foo/bar/my-plugin.gradle.kts` i have:

plugins {
  `java-library`
}
...
tasks.withType<JavaCompile> {
    options.isWarnings = true
    options.compilerArgs = listOf("-Xlint:all,-options,-serial,-processing")
}
```

which works just fine. as SOON as i add in an external plugin, say 
`id("org.owasp.dependencycheck")`
(which has it's version fixed in the `build.gradle.kts`) 

i get 

```
e: /Users/me/dev/src/glassdoor/foo/buildSrc/src/main/kotlin/com/glassdoor/sbat/gradle/java-library-convention.gradle.kts: (29, 1): Expression 'java' cannot be invoked as a function. The function 'invoke()' is not found
e: /Users/me/dev/src/foo/buildSrc/src/main/kotlin/com/glassdoor/sbat/gradle/java-library-convention.gradle.kts: (29, 1): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
```

**Comment by stellingsimon** [comment]
@madorb:

> as SOON as i add in an external plugin, say
> `id("org.owasp.dependencycheck")`
> (which has it's version fixed in the `build.gradle.kts`)

I hit exactly the same problem. Due to the rather misleading error messages, it took me a while to realize that a missing `dependencies {}` declaration was the problem.

The detailed problem and solution are documented Q&A-style in [this StackOverflow answer](https://stackoverflow.com/a/58826818/484293).

@bamboo This misunderstanding prevented me from structuring my Gradle build meaningfully into a set of pre-compiled script plugins, and after several days of fruitless efforts I was close to reverting to a Groovy-based Gradle build. Unless/until the error messages for this specific case are improved I think this would warrant an additional example in `kotlin-dsl-samples`. I may be able to provide a PR if you agree. Please advise :-)
