### ISSUE TITLE
KT-22473 - IntelliJ and Android Studio treat `settings.gradle.kts` as a Project script instead of a Settings script

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#685]
https://youtrack.jetbrains.com/issue/KT-22473

**Comment by ingokegel** [comment]
Not only Android Studio, also IntelliJ IDEA. Maybe since Kotlin 1.2.20.

**Comment by GFriedrich** [comment]
Yes, looks like this is broken when using the latest Kotlin plugin for any IntelliJ IDE. Rolled back to 1.2.10 and it's working again.

**Comment by GFriedrich** [comment]
Kotlin Plugin 1.2.21 is still affected.

**Comment by soberich** [comment]
Hi, 
I recently [posted ](https://github.com/gradle/kotlin-dsl/issues/658#issuecomment-357959779) that syntax highlight is fine in last IDEA build, but since then I found out (at last) that there is a OS dependent appearence. 
I had same Ultimate editions of previous builds and the recent one on 
Windows 7 Ultimate (x64) - settings.gradle.kts syntax highlight is broken (even after complete reinstall of IDEA)
Windows 10 Enterprise (x64) - settings.gradle.kts syntax highlight is all good

IntelliJ IDEA 2018.1 EAP (Ultimate Edition)
Build #IU-181.3007.14, built on January 24, 2018
IntelliJ IDEA EAP User
Expiration date: February 23, 2018
JRE: 1.8.0_152-release-1136-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by ligee** [comment]
It is fixed in the upcoming 1.2.30 (the first EAP will be published quite soon).

**Comment by GFriedrich** [comment]
1.2.30 was just released and the bug is gone.
Yay! :)

**Comment by IgorGanapolsky** [comment]
This is still broken in A.S. 3.6
