### ISSUE TITLE
Redistribute modified Trove sources

### ISSUE THREAD

**Issue by cbeams** [gradle/kotlin-dsl#70]

**Comment by cbeams** [comment]
@yole, we discussed this topic briefly, and it sounds like we (gradle-script-kotlin) will indeed need to redistribute Trove sources. Could you say a little bit more about how you guys handle that on the IDEA side, and what might be a sensible approach to redistribution with regard to GSK and/or the Gradle distribution itself?

**Comment by yole** [comment]
The way we do it is by including a source jar file for Trove in the "lib/src" directory of the IntelliJ IDEA distribution. The source jar contains the code itself and a text file documenting our changes compared to the upstream version. The file itself is here: https://github.com/JetBrains/intellij-community/blob/master/lib/src/trove4j_src.jar

If I remember correctly, we discussed that approach with the Trove developers and they found it acceptable.

For the Kotlin compiler, we're most likely going to do a similar thing, and put it under lib/src. (We'll include the Trove sources in the standalone compiler distribution, but it doesn't seem to make sense to include it in the plugin, because IntelliJ, into which the plugin is installed, has a copy of the sources already.)

Not sure how exactly Kotlin would be bundled into Gradle, so I can't suggest anything specific yet.

**Comment by cbeams** [comment]
Thanks, @yole. That's exactly the information I needed.

**Comment by bamboo** [comment]
Resolved by gradle/gradle#5847
