### ISSUE TITLE
Make IDE resolver provide correct source path for precompiled script plugins

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#795]
The source path of a precompiled script plugin should be the one of its enclosing source-set.

**Comment by sic-bre** [comment]
Is this going to resolve the issues I've pointed out in the sample I've posted at [precompiled-script-plugin-sample](https://github.com/sic-bre/precompiled-script-plugin-sample.git)?  My current use case is using buildSrc project to modularize a top level build into various binary kotlin-dsl plugins.

1) A "precompiled" plugin in the IDE doesn't go to the original source.  When loading from a binary repository I would expect that a sources.jar could (optionally) be included with the plugin.  When running from a buildSrc project I would expect to navigate to the to the actual plugin source code in the buildSrc Gradle project.

2) A "standard" kotlin-dsl plugin has no way to get the full dsl (such as the generated accessors)

3) Extra configuration is required for a "standard" kotlin-dsl plugin.  With the precompiled plugins there does not appear to be a way to override the default conventions on naming plugins and their string id for the plugins block.

In general for the work that I'm doing now I can only use the standard plugins as the precompiled plugins don't provide the development navigation and refactoring support in the Intellij yet.  I'm trying to figure out if this is a temporary thing that will be fixed by this issue or if I need to open new issues.

**Comment by bamboo** [comment]
Hi @sic-bre,

Thanks for the feedback.

> A "precompiled" plugin in the IDE doesn't go to the original source.

The `Plugin<*>` implementation class will have a link to the original precompiled script plugin to allow the navigation. 

> A "standard" kotlin-dsl plugin has no way to get the full dsl (such as the generated accessors)

#673 will let a plugin project declare its dependencies on external plugins, including the ability to ask for static accessors to the dynamic model elements contributed by those plugins.

> Extra configuration is required for a "standard" kotlin-dsl plugin.

Yes. An annotation processor could help here.

> With the precompiled plugins there does not appear to be a way to override the default conventions on naming plugins and their string id for the plugins block.

The id of a precompiled script plugin is derived from its package declaration and file name by a simple convention. It would be interesting to know which limitations you are running into for currently we have no plans of introducing an override mechanism.

**Comment by bamboo** [comment]
Navigating to sources from precompiled script plugins work as expected:

![Precompiled script plugin](https://user-images.githubusercontent.com/51689/43804049-1997f414-9a71-11e8-88f4-5d14827d9482.gif)
