### ISSUE TITLE
Potential problem in Lexer

### ISSUE THREAD

**Issue by oehme** [gradle/kotlin-dsl#858]
I just got a build failure caused by the Kotlin Lexer not being able to process one of our precompiled scripts: https://builds.gradle.org/viewLog.html?buildId=12619556&buildTypeId=Gradle_Check_Platform_Java8_Oracle_Windows_toolingApiBuilders&tab=buildLog

**Comment by bamboo** [comment]
Hm, we had problems with the lexer on Windows before and the fix included a call to `setIdeaIoUseFallback()`

https://github.com/gradle/kotlin-dsl/blob/e1a19b2b552fd1dc08d0455b7def529e5ee670fc/provider/src/main/kotlin/org/gradle/kotlin/dsl/provider/CachingKotlinCompiler.kt#L81

Maybe that's happening too late in that case since the code path to extract the package name doesn't guarantee `CachingKotlinCompiler` will be initialized.

Curiously, somewhere else we actually convert the line separators before giving the string to the lexer:

https://github.com/gradle/kotlin-dsl/blob/6e0ddfc1890a79821255a6df3e246218eeff22e9/provider/src/main/kotlin/org/gradle/kotlin/dsl/provider/KotlinBuildScriptCompiler.kt#L63

**Comment by bamboo** [comment]
Resolved in 88d3836.
