### ISSUE TITLE
Let container scope string invoke be `named`

### ISSUE THREAD

**Issue by bamboo** [gradle/kotlin-dsl#907]
The string invoke syntax on containers provides the shortest idiom for configuring elements but Its `maybeCreate` semantics is confusing and error-prone.

Considering that _configuring new elements_  is more common than _registering existing elements_  and that the `register(...) { ... }` syntax provides a convenient and clear replacement for the register  element_ scenario, the string invoke syntax semantics should be changed to `named`.

This requires the lazy API to be moved up in the Gradle container hierarchy: gradle/gradle-native#680.

**Comment by gildor** [comment]
I disagree that "registering new elements is more common than configuring existing elements".
It's true for any kind DSL, except one very important: tasks.
Task configuration is a very common thing and uses invoke syntax. The situation can be improved if plugins migrate their configs from tasks to extensions, but now even Kotlin plugin or core Gradle plugins have a lot of features configured only by task configuration
But a big problem with tasks configuration is it's really ugly because for tasks you usually need type and invoke syntax doesn't support reified generics.
Maybe make sense to deprecate this syntax for tasks and be explicit and use `named`, `create` etc functions instead.

**Comment by mkobit** [comment]
An additional consideration that I have seen with the string invocation DSL is unintentional creation when configuration was desired. For example

```kotlin
tasks {
  "asemble" {
    dependsOn(myTask)
  }
}
```

A typo of `assemble` to `assemble` doesn't lead to an error message here. A `maybeCreate` with the task is created and if the tasks aren't inspected closely it could be difficult to catch that your intended dependencies did not execute during the build.

**Comment by gildor** [comment]
@mkobit really good point why implicit creation of tasks is bad practice 👍

**Comment by eskatos** [comment]
Thanks for the feedback @gildor and @mkobit!
After discussing this we changed to let container scope string invoke be `named`.
